name: Draw.io to PNG

on:
  push:
    paths:
      - 'original_bot.drawio'

jobs:
  convert:
    runs-on: ubuntu-latest # 実行環境
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install drawio-export
        run: npm install -g drawio-export

      - name: Convert .drawio to .png
        run: |
          for file in $(find . -name "*.drawio"); do
            drawio-export --output "$(dirname "$file")/$(basename "$file" .drawio).png" "$file"
          done

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Auto-convert .drawio to .png"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
