name: Draw.io to PNG

on:
  push:
    paths:
      - 'original_bot.drawio' # pushした時に、original_bot.drawioが変更されていたら実行
  workflow_dispatch: # 手動実行も可能にする。

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install draw.io
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2 libgbm1 libgtk-3-0 libnss3 xvfb
          npm install -g drawio-desktop

      - name: Convert .drawio to .png
        run: |
          for file in $(find . -name "*.drawio"); do
            xvfb-run --auto-servernum drawio -x -f png -o "$(dirname "$file")/$(basename "$file" .drawio).png" "$file"
          done

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Auto-convert .drawio to .png" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

